Update bl

diff --git a/bl b/bl
--- a/bl
+++ b/bl
@@ -3,7 +3,7 @@ use strict;
 use warnings;
 
 my( $OS_Version,$Locale,%JA );
-my $MY_BREW = `CO=\$(which brew);printf \${CO%/bin/brew} 2>/dev/null` || die " brew path not found\n";
+my $MY_BREW = `CO=\$(command -v brew);printf \${CO%/bin/brew} 2>/dev/null` || die " brew not found\n";
 
 MAIN:{
  my $home = "$ENV{'HOME'}/.BREW_LIST";
@@ -183,7 +183,7 @@ sub Died_1{
    # Uninstall : rm -rf ~/.BREW_LIST $MY_BREW/share/zsh/site-functions/_bl\n   $brew" :
    "\n   # Uninstall : rm -rf ~/.BREW_LIST $MY_BREW/share/zsh/site-functions/_bl\n   $brew";
   print"\033[?7l" if -t STDOUT;
-  print"  Enhanced brew list : version 1.25_1\n   Option\n  -new\t:  creat new cache : argument '.' rmdir WAIT
+  print"  Enhanced brew list : version 1.25_2\n   Option\n  -new\t:  creat new cache : argument '.' rmdir WAIT
   -l\t:  formula list : First argument Formula search : Second argument '.' Full-text search
   -i\t:  instaled formula list\n  -\t:  brew list command\n  -lb\t:  bottled install formula list
   -lx\t:  can't install formula list\n  -s\t:  type search formula name
@@ -1974,7 +1974,7 @@ if [[ $2 ]];then
    git clone -q https://github.com/konnano/JA_BREW ~/.JA_BREWG 2>/dev/null || { math_rm; ${die:?git clone error}; }
     cp ~/.JA_BREWG/* ~/.JA_BREW/
      rm -rf ~/.JA_BREWG ~/.JA_BREW/.git
-    [[ $NAME = Linux ]] && rm ~/.JA_BREW/ja_cask.txt ~/.JA_BREW/ja_tap.txt
+    [[ $NAME = Linux ]] && rm ~/.JA_BREW/{ja_cask.txt,ja_tap.txt}
     [[ $NAME = Darwin ]] && rm ~/.JA_BREW/ja_linux.txt
   fi
  fi
@@ -2218,7 +2218,7 @@ use Fcntl ':DEFAULT';
 
 my( $re,$OS_Version,$OS_Version2,%MAC_OS,%Mac_OS,$Xcode,%HAN,@BREW,@CASK,$NAM,$ACA,$FON,@FONT );
 my $UNAME = `uname -m` !~ /arm64|aarch64/ ? 'x86_64' : 'arm64';
-my $MY_BREW = $ENV{'Perl_B'}||`CO=\$(which brew);printf \${CO%/bin/brew} 2>/dev/null`||die" brew path not found\n";
+my $MY_BREW = $ENV{'Perl_B'}||`CO=\$(command -v brew);printf \${CO%/bin/brew} 2>/dev/null`||die" brew not found\n";
 my $MY_HOME = -d "$MY_BREW/Homebrew" ? "$MY_BREW/Homebrew" : $MY_BREW;
 
 if( $^O eq 'darwin' ){ $re->{'MAC'} = 1;
