Update bl

diff --git a/bl b/bl
--- a/bl
+++ b/bl
@@ -3,7 +3,7 @@ use strict;
 use warnings;
 
 my( $OS_Version,$Locale,%JA );
-my $MY_BREW = `CO=\$(command -v brew);printf \${CO%/bin/brew} 2>/dev/null`||die " brew not found\n";
+my $MY_BREW = `CO=\$(command -v brew);printf "\${CO%/bin/brew}" 2>/dev/null`||die " brew not found\n";
 
 MAIN:{
  my $home = "$ENV{'HOME'}/.BREW_LIST";
@@ -1954,14 +1954,14 @@ __END__
 
  math_rm(){
   [[ $1 = 1 ]] && rm -f ~/.BREW_LIST/{*.html,DBM*} || rm -f ~/.BREW_LIST/*.html
-                  rm -rf ~/.JA_BREWG ~/.BREW_LIST/{homebrew*,{0..19},parse,cparse,FONT_*,TIE_*,WAIT$CO,LOCK}; }
+                  rm -rf ~/.JA_BREWG ~/.BREW_LIST/{homebrew*,{0..19},parse,cparse,FONT_*,TIE_*,"WAIT$CO",LOCK}; }
 
 if ! printf -v TI '%(%s)T' 2>/dev/null;then
  TI=$(date +%s)
 fi
 
 if [[ $1 = 1 && -d ~/.BREW_LIST/LOCK ]];then
- LS1=$(( $(date -r ~/.BREW_LIST/LOCK +%s)+60 ))
+ LS1=$(( $(date -r ~/.BREW_LIST/LOCK +%s)+120 ))
   (( TI > LS1 )) && math_rm
 fi
 
@@ -1972,6 +1972,11 @@ if [[ $2 ]];then
  trap 'math_rm 1; exit 1' 1 2 3 15
 
   cd ~/.BREW_LIST || { math_rm; ${die:?cd error}; }
+ for WT in WAIT*;do
+  [[ ${WT: -1} = '*' ]] && continue
+  WS1=$(( $(date -r "$WT" +%s)+1800 ))
+   (( TI > WS1 )) && rmdir "$WT"
+ done
  for WA in {WAIT*,Tree*,File*=*};do
   [[ ${WA: -1} = '*' ]] && continue || shopt -s extglob
   if ! kill -0 "${WA/+(WAIT|Tree|File*=)/}" 2>/dev/null;then
@@ -2031,7 +2036,7 @@ if [[ $2 ]];then
     { math_rm; ${die:?curl e error}; }
      rmdir ~/.BREW_LIST/8
   fi
-   export Perl_B=$(CO=$(command -v brew);echo ${CO%/bin/brew})
+   export Perl_B=$(CO=$(command -v brew);echo "${CO%/bin/brew}")
     [[ ! $Perl_B ]] && { math_rm; ${die:?brew path not found}; }
 
   if [[ $2 = 1 ]];then
@@ -2113,7 +2118,7 @@ EOF
      { math_rm; ${die:?curl r error}; }
   fi
    unzip -q ~/.BREW_LIST/font.zip -d ~/.BREW_LIST || { math_rm 1; ${die:?unzip 3 error}; }
-   export Perl_B=$(CO=$(command -v brew);echo ${CO%/bin/brew})
+   export Perl_B=$(CO=$(command -v brew);echo "${CO%/bin/brew}")
     [[ ! $Perl_B ]] && { math_rm; ${die:?brew path not found}; }
 perl<<"EOF"
    $MY_HOME = -d "$ENV{'Perl_B'}/Homebrew" ? "$ENV{'Perl_B'}/Homebrew" : $ENV{'Perl_B'};
@@ -2227,7 +2232,7 @@ use Fcntl ':DEFAULT';
 
 my( $re,$OS_Version,$OS_Version2,%MAC_OS,%Mac_OS,$Xcode,%HAN,@BREW,@CASK,$NAM,$ACA,$FON,@FONT );
 my $UNAME = `uname -m` !~ /arm64|aarch64/ ? 'x86_64' : 'arm64';
-my $MY_BREW = $ENV{'Perl_B'}||`CO=\$(command -v brew);printf \${CO%/bin/brew} 2>/dev/null`||die" brew not found\n";
+my $MY_BREW = $ENV{'Perl_B'}||`CO=\$(command -v brew);printf "\${CO%/bin/brew}" 2>/dev/null`||die" brew not found\n";
 my $MY_HOME = -d "$MY_BREW/Homebrew" ? "$MY_BREW/Homebrew" : $MY_BREW;
 
 if( $^O eq 'darwin' ){ $re->{'MAC'} = 1;
@@ -2236,7 +2241,7 @@ if( $^O eq 'darwin' ){ $re->{'MAC'} = 1;
    $OS_Version =~ s/^(1[1-5]).+\n/$1.0/;
  $OS_Version2 = $UNAME eq 'arm64' ? "${OS_Version}M1" : $OS_Version;
  unless( $ARGV[0] ){
-  $Xcode = `CC=\$(xcode-select -p);cat \${CC%/*}/version.plist 2>/dev/null|
+  $Xcode = `CC=\$(xcode-select -p);cat "\${CC%/*}"/version.plist 2>/dev/null|
             sed -nE '/ShortVersionString/{n;s/[^0-9]+([0-9.]+).+/\\1/;s/^([1-9]\\.)/0\\1/;p;q;}'`||0;
  }
   %Mac_OS = ('sequoia'=>'15.0','sonoma'=>'14.0','ventura'=>'13.0','monterey'=>'12.0','big_sur'=>'11.0',
